# Generated by Django 5.1.7 on 2025-03-25 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0010_alter_equipe_formacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monografias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('discente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipe.equipe')),
            ],
        ),
    ]
