# Generated by Django 5.1.7 on 2025-04-09 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0011_alter_equipe_formacao'),
        ('monografias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monografias',
            name='coorientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coorientador', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='monografias',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monografias',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to='equipe.equipe'),
        ),
    ]
