# Generated by Django 5.1.7 on 2025-06-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monografias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='github',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='google_scholar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='lattes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='orcid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='research_gate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
