# Generated by Django 5.1.7 on 2025-04-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monografias', '0002_monografias_coorientador_monografias_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monografias',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='equipes/pdfs/'),
        ),
    ]
