# Generated by Django 5.1.7 on 2025-04-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monografias', '0003_monografias_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monografias',
            name='pdf',
        ),
    ]
