# Generated by Django 5.1.7 on 2025-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_alter_equipe_formacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='formacao',
            field=models.CharField(choices=[('M', 'Mestrado'), ('D', 'Doutorado'), ('G', 'Graduação')], default='G', max_length=30),
        ),
    ]
