# Generated by Django 5.1.7 on 2025-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0004_equipe_email_alter_equipe_formacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='formacao',
            field=models.CharField(choices=[('G', 'Graduação'), ('D', 'Doutorado'), ('M', 'Mestrado')], default='G', max_length=30),
        ),
    ]
