# Generated by Django 5.1.7 on 2025-03-24 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0005_alter_equipe_formacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='registro_atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='registro_criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipe',
            name='formacao',
            field=models.CharField(choices=[('M', 'Mestrado'), ('D', 'Doutorado'), ('G', 'Graduação')], default='G', max_length=30),
        ),
    ]
