# Generated by Django 5.1.7 on 2025-03-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0006_equipe_registro_atualizado_equipe_registro_criado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='formacao',
            field=models.CharField(choices=[('D', 'Doutorado'), ('G', 'Graduação'), ('M', 'Mestrado')], default='G', max_length=30),
        ),
    ]
