# Generated by Django 5.1.7 on 2025-03-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0007_alter_equipe_formacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='google_scholar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='lattes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='orcid',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='research_gate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='formacao',
            field=models.CharField(choices=[('M', 'Mestrado'), ('D', 'Doutorado'), ('G', 'Graduação')], default='G', max_length=30),
        ),
    ]
