# Generated by Django 5.1.7 on 2025-03-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0008_equipe_github_equipe_google_scholar_equipe_lattes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='formacao',
            field=models.CharField(choices=[('M', 'Mestrado'), ('G', 'Graduação'), ('D', 'Doutorado')], default='G', max_length=30),
        ),
    ]
