# Generated by Django 5.1.7 on 2025-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0011_alter_equipe_formacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='formacao',
            field=models.CharField(choices=[('G', 'Graduação'), ('D', 'Doutorado'), ('M', 'Mestrado')], default='G', max_length=30),
        ),
    ]
