# Generated by Django 5.1.7 on 2025-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0013_alter_equipe_formacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='equipes/pdfs/'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='formacao',
            field=models.CharField(choices=[('D', 'Doutorado'), ('G', 'Graduação'), ('M', 'Mestrado')], default='G', max_length=30),
        ),
    ]
