# Generated by Django 5.1.7 on 2025-06-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0014_equipe_pdf_alter_equipe_formacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='formacao',
            field=models.CharField(choices=[('D', 'Doutorado'), ('M', 'Mestrado'), ('G', 'Graduação')], default='G', max_length=30),
        ),
    ]
