# Generated by Django 5.1.7 on 2025-06-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0015_alter_equipe_formacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='formacao',
            field=models.CharField(choices=[('D', 'Doutorado'), ('G', 'Graduação'), ('M', 'Mestrado')], default='G', max_length=30),
        ),
    ]
